name: "LocalDashboard"
description: >
  Start X server and launch dashboard from browser on local HAOS server (Jeff Kosowsky)
version: "0.9.0"
slug: "localdashboard"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
host_network: true
host_dbus: true
init: false

devices:
  - /dev/dri
  - /dev/fb0
  - /dev/fb1
  - /dev/input/event0
  - /dev/input/event1

privileged:
  - SYS_ADMIN

security_opt:
  - apparmor:unconfined

options:
  start_url: "http://localhost:8123"
  login_delay: 2
  hdmi_port: 0
  screen_timeout: 0
  browser_refresh: 600

schema:
  ha_username: str
  ha_password: password
  start_url: str
  login_delay: int(0,)
  hdmi_port: int(0,1)
  screen_timeout: int(0,)
  browser_refresh: int(0,)

environment:
  DISPLAY: ":0"
